// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatWhere.Data.Concrete.EfCore.Context;

#nullable disable

namespace WhatWhere.Data.Migrations
{
    [DbContext(typeof(WhatWhereContext))]
    [Migration("20230711124916_DataDb")]
    partial class DataDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("WhatWhere.Entity.Concrete.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bosses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthOfYear = 1990,
                            FirstName = "Ahmet",
                            Gender = "Male",
                            LastName = "Yılmaz",
                            MailAdress = "ahmet@example.com",
                            PhoneNumber = "1234567890",
                            Url = "ahmet-yilmaz.com"
                        },
                        new
                        {
                            Id = 2,
                            BirthOfYear = 1985,
                            FirstName = "Mehmet",
                            Gender = "Male",
                            LastName = "Kaya",
                            MailAdress = "mehmet@example.com",
                            PhoneNumber = "1234567890",
                            Url = "mehmet-kaya.com"
                        },
                        new
                        {
                            Id = 3,
                            BirthOfYear = 1992,
                            FirstName = "Ayşe",
                            Gender = "Female",
                            LastName = "Demir",
                            MailAdress = "ayse@example.com",
                            PhoneNumber = "1234567890",
                            Url = "ayse-demir.com"
                        },
                        new
                        {
                            Id = 4,
                            BirthOfYear = 1988,
                            FirstName = "Fatma",
                            Gender = "Female",
                            LastName = "Yıldırım",
                            MailAdress = "fatma@example.com",
                            PhoneNumber = "1234567890",
                            Url = "fatma-yildirim.com"
                        },
                        new
                        {
                            Id = 5,
                            BirthOfYear = 1995,
                            FirstName = "Ali",
                            Gender = "Male",
                            LastName = "Öztürk",
                            MailAdress = "ali@example.com",
                            PhoneNumber = "1234567890",
                            Url = "ali-ozturk.com"
                        },
                        new
                        {
                            Id = 6,
                            BirthOfYear = 1991,
                            FirstName = "Zeynep",
                            Gender = "Female",
                            LastName = "Aktaş",
                            MailAdress = "zeynep@example.com",
                            PhoneNumber = "1234567890",
                            Url = "zeynep-aktas.com"
                        },
                        new
                        {
                            Id = 7,
                            BirthOfYear = 1987,
                            FirstName = "Hakan",
                            Gender = "Male",
                            LastName = "Koç",
                            MailAdress = "hakan@example.com",
                            PhoneNumber = "1234567890",
                            Url = "hakan-koc.com"
                        },
                        new
                        {
                            Id = 8,
                            BirthOfYear = 1994,
                            FirstName = "Selin",
                            Gender = "Female",
                            LastName = "Can",
                            MailAdress = "selin@example.com",
                            PhoneNumber = "1234567890",
                            Url = "selin-can.com"
                        },
                        new
                        {
                            Id = 9,
                            BirthOfYear = 1989,
                            FirstName = "Murat",
                            Gender = "Male",
                            LastName = "Şahin",
                            MailAdress = "murat@example.com",
                            PhoneNumber = "1234567890",
                            Url = "murat-sahin.com"
                        },
                        new
                        {
                            Id = 10,
                            BirthOfYear = 1993,
                            FirstName = "Deniz",
                            Gender = "Female",
                            LastName = "Arslan",
                            MailAdress = "deniz@example.com",
                            PhoneNumber = "1234567890",
                            Url = "deniz-arslan.com"
                        });
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kasap Kategorisi",
                            Name = "Kasap"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eczane Kategorisi",
                            Name = "Eczane"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kırtasiye Kategorisi",
                            Name = "Kırtasiye"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Terzi Kategorisi",
                            Name = "Terzi"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Dişçi Kategorisi",
                            Name = "Dişçi"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kiralık Katil Kategorisi",
                            Name = "Kiralık Katil"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Gym Kategorisi",
                            Name = "Gym"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Mantıcı Kategorisi",
                            Name = "Mantıcı"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Futbol Sahası Kategorisi",
                            Name = "Futbol Sahası"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lostra Kategorisi",
                            Name = "Lostra"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bakkal Kategorisi",
                            Name = "Bakkal"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Restoran Kategorisi",
                            Name = "Restoran"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Kafe Kategorisi",
                            Name = "Kafe"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Butik Kategorisi",
                            Name = "Butik"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Optik Kategorisi",
                            Name = "Optik"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Mobilya Mağazası Kategorisi",
                            Name = "Mobilya Mağazası"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Oyuncakçı Kategorisi",
                            Name = "Oyuncakçı"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Elektronik Mağaza Kategorisi",
                            Name = "Elektronik Mağaza"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Çiçekçi Kategorisi",
                            Name = "Çiçekçi"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Kitapçı Kategorisi",
                            Name = "Kitapçı"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Genel Kategorisi",
                            Name = "Genel"
                        });
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ilce = "Aladağ,Ceyhan,Çukurova,Feke,İmamoğlu,Karaisalı,Karataş,Kozan,Pozantı,Saimbeyli,Sarıçam,Seyhan,Tufanbeyli,Yumurtalık,Yüreğir",
                            Sehir = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            Ilce = "Besni,Çelikhan,Gerger,Gölbaşı,Kahta,Merkez,Samsat,Sincik,Tut",
                            Sehir = "Adıyaman"
                        },
                        new
                        {
                            Id = 3,
                            Ilce = "Başmakçı,Bayat,Bolvadin,Çay,Çobanlar,Dazkırı,Dinar,Emirdağ,Evciler,Hocalar,İhsaniye,İscehisar,Kızılören,Merkez,Sandıklı,Sinanpaşa,Sultandağı,Şuhut",
                            Sehir = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = 4,
                            Ilce = "Diyadin,Doğubayazıt,Eleşkirt,Hamur,Merkez,Patnos,Taşlıçay,Tutak",
                            Sehir = "Ağrı"
                        },
                        new
                        {
                            Id = 5,
                            Ilce = "Göynücek,Gümüşhacıköy,Hamamözü,Merkez,Merzifon,Suluova,Taşova",
                            Sehir = "Amasya"
                        },
                        new
                        {
                            Id = 6,
                            Ilce = "Altındağ,Ayaş,Bala,Beypazarı,Çamlıdere,Çankaya,Çubuk,Elmadağ,Güdül,Haymana,Kalecik,Kızılcahamam,Nallıhan,Polatlı,Şereflikoçhisar,Yenimahalle,Gölbaşı,Keçiören,Mamak,Sincan,Kazan,Akyurt,Etimesgut,Evren,Pursaklar",
                            Sehir = "Ankara"
                        },
                        new
                        {
                            Id = 7,
                            Ilce = "Akseki,Alanya,Elmalı,Finike,Gazipaşa,Gündoğmuş,Kaş,Korkuteli,Kumluca,Manavgat,Serik,Demre,İbradı,Kemer,Aksu,Döşemealtı,Kepez,Konyaaltı,Muratpaşa",
                            Sehir = "Antalya"
                        },
                        new
                        {
                            Id = 8,
                            Ilce = "Ardanuç,Arhavi,Merkez,Borçka,Hopa,Şavşat,Yusufeli,Murgul",
                            Sehir = "Artvin"
                        },
                        new
                        {
                            Id = 9,
                            Ilce = "Merkez,Bozdoğan,Efeler,Çine,Germencik,Karacasu,Koçarlı,Kuşadası,Kuyucak,Nazilli,Söke,Sultanhisar,Yenipazar,Buharkent,İncirliova,Karpuzlu,Köşk,Didim",
                            Sehir = "Aydın"
                        },
                        new
                        {
                            Id = 10,
                            Ilce = "Altıeylül,Ayvalık,Merkez,Balya,Bandırma,Bigadiç,Burhaniye,Dursunbey,Edremit,Erdek,Gönen,Havran,İvrindi,Karesi,Kepsut,Manyas,Savaştepe,Sındırgı,Gömeç,Susurluk,Marmara",
                            Sehir = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            Ilce = "Merkez,Bozüyük,Gölpazarı,Osmaneli,Pazaryeri,Söğüt,Yenipazar,İnhisar",
                            Sehir = "Bilecik"
                        },
                        new
                        {
                            Id = 12,
                            Ilce = "Merkez,Genç,Karlıova,Kiğı,Solhan,Adaklı,Yayladere,Yedisu",
                            Sehir = "Bingöl"
                        },
                        new
                        {
                            Id = 13,
                            Ilce = "Adilcevaz,Ahlat,Merkez,Hizan,Mutki,Tatvan,Güroymak",
                            Sehir = "Bitlis"
                        },
                        new
                        {
                            Id = 14,
                            Ilce = "Merkez,Gerede,Göynük,Kıbrıscık,Mengen,Mudurnu,Seben,Dörtdivan,Yeniçağa",
                            Sehir = "Bolu"
                        },
                        new
                        {
                            Id = 15,
                            Ilce = "Ağlasun,Bucak,Merkez,Gölhisar,Tefenni,Yeşilova,Karamanlı,Kemer,Altınyayla,Çavdır,Çeltikçi",
                            Sehir = "Burdur"
                        },
                        new
                        {
                            Id = 16,
                            Ilce = "Gemlik,İnegöl,İznik,Karacabey,Keles,Mudanya,Mustafakemalpaşa,Orhaneli,Orhangazi,Yenişehir,Büyükorhan,Harmancık,Nilüfer,Osmangazi,Yıldırım,Gürsu,Kestel",
                            Sehir = "Bursa"
                        },
                        new
                        {
                            Id = 17,
                            Ilce = "Ayvacık,Bayramiç,Biga,Bozcaada,Çan,Merkez,Eceabat,Ezine,Gelibolu,Gökçeada,Lapseki,Yenice",
                            Sehir = "Çanakkale"
                        },
                        new
                        {
                            Id = 18,
                            Ilce = "Merkez,Çerkeş,Eldivan,Ilgaz,Kurşunlu,Orta,Şabanözü,Yapraklı,Atkaracalar,Kızılırmak,Bayramören,Korgun",
                            Sehir = "Çankırı"
                        },
                        new
                        {
                            Id = 19,
                            Ilce = "Alaca,Bayat,Merkez,İskilip,Kargı,Mecitözü,Ortaköy,Osmancık,Sungurlu,Boğazkale,Uğurludağ,Dodurga,Laçin,Oğuzlar",
                            Sehir = "Çorum"
                        },
                        new
                        {
                            Id = 20,
                            Ilce = "Acıpayam,Buldan,Çal,Çameli,Çardak,Çivril,Merkez,Merkezefendi,Pamukkale,Güney,Kale,Sarayköy,Tavas,Babadağ,Bekilli,Honaz,Serinhisar,Baklan,Beyağaç,Bozkurt",
                            Sehir = "Denizli"
                        },
                        new
                        {
                            Id = 21,
                            Ilce = "Kocaköy,Çermik,Çınar,Çüngüş,Dicle,Ergani,Hani,Hazro,Kulp,Lice,Silvan,Eğil,Bağlar,Kayapınar,Sur,Yenişehir,Bismil",
                            Sehir = "Diyarbakır"
                        },
                        new
                        {
                            Id = 22,
                            Ilce = "Merkez,Enez,Havsa,İpsala,Keşan,Lalapaşa,Meriç,Uzunköprü,Süloğlu",
                            Sehir = "Edirne"
                        },
                        new
                        {
                            Id = 23,
                            Ilce = "Ağın,Baskil,Merkez,Karakoçan,Keban,Maden,Palu,Sivrice,Arıcak,Kovancılar,Alacakaya",
                            Sehir = "Elazığ"
                        },
                        new
                        {
                            Id = 24,
                            Ilce = "Çayırlı,Merkez,İliç,Kemah,Kemaliye,Refahiye,Tercan,Üzümlü,Otlukbeli",
                            Sehir = "Erzincan"
                        },
                        new
                        {
                            Id = 25,
                            Ilce = "Aşkale,Çat,Hınıs,Horasan,İspir,Karayazı,Narman,Oltu,Olur,Pasinler,Şenkaya,Tekman,Tortum,Karaçoban,Uzundere,Pazaryolu,Köprüköy,Palandöken,Yakutiye,Aziziye",
                            Sehir = "Erzurum"
                        },
                        new
                        {
                            Id = 26,
                            Ilce = "Çifteler,Mahmudiye,Mihalıççık,Sarıcakaya,Seyitgazi,Sivrihisar,Alpu,Beylikova,İnönü,Günyüzü,Han,Mihalgazi,Odunpazarı,Tepebaşı",
                            Sehir = "Eskişehir"
                        },
                        new
                        {
                            Id = 27,
                            Ilce = "Araban,İslahiye,Nizip,Oğuzeli,Yavuzeli,Şahinbey,Şehitkamil,Karkamış,Nurdağı",
                            Sehir = "Gaziantep"
                        },
                        new
                        {
                            Id = 28,
                            Ilce = "Alucra,Bulancak,Dereli,Espiye,Eynesil,Merkez,Görele,Keşap,Şebinkarahisar,Tirebolu,Piraziz,Yağlıdere,Çamoluk,Çanakçı,Doğankent,Güce",
                            Sehir = "Giresun"
                        },
                        new
                        {
                            Id = 29,
                            Ilce = "Merkez,Kelkit,Şiran,Torul,Köse,Kürtün",
                            Sehir = "Gümüşhane"
                        },
                        new
                        {
                            Id = 30,
                            Ilce = "Çukurca,Merkez,Şemdinli,Yüksekova",
                            Sehir = "Hakkari"
                        },
                        new
                        {
                            Id = 31,
                            Ilce = "Altınözü,Arsuz,Defne,Dörtyol,Hassa,Antakya,İskenderun,Kırıkhan,Payas,Reyhanlı,Samandağ,Yayladağı,Erzin,Belen,Kumlu",
                            Sehir = "Hatay"
                        },
                        new
                        {
                            Id = 32,
                            Ilce = "Atabey,Eğirdir,Gelendost,Merkez,Keçiborlu,Senirkent,Sütçüler,Şarkikaraağaç,Uluborlu,Yalvaç,Aksu,Gönen,Yenişarbademli",
                            Sehir = "Isparta"
                        },
                        new
                        {
                            Id = 33,
                            Ilce = "Anamur,Erdemli,Gülnar,Mut,Silifke,Tarsus,Aydıncık,Bozyazı,Çamlıyayla,Akdeniz,Mezitli,Toroslar,Yenişehir",
                            Sehir = "Mersin"
                        },
                        new
                        {
                            Id = 34,
                            Ilce = "Adalar,Bakırköy,Beşiktaş,Beykoz,Beyoğlu,Çatalca,Eyüp,Fatih,Gaziosmanpaşa,Kadıköy,Kartal,Sarıyer,Silivri,Şile,Şişli,Üsküdar,Zeytinburnu,Büyükçekmece,Kağıthane,Küçükçekmece,Pendik,Ümraniye,Bayrampaşa,Avcılar,Bağcılar,Bahçelievler,Güngören,Maltepe,Sultanbeyli,Tuzla,Esenler,Arnavutköy,Ataşehir,Başakşehir,Beylikdüzü,Çekmeköy,Esenyurt,Sancaktepe,Sultangazi",
                            Sehir = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            Ilce = "Aliağa,Bayındır,Bergama,Bornova,Çeşme,Dikili,Foça,Karaburun,Karşıyaka,Kemalpaşa,Kınık,Kiraz,Menemen,Ödemiş,Seferihisar,Selçuk,Tire,Torbalı,Urla,Beydağ,Buca,Konak,Menderes,Balçova,Çiğli,Gaziemir,Narlıdere,Güzelbahçe,Bayraklı,Karabağlar",
                            Sehir = "İzmir"
                        },
                        new
                        {
                            Id = 36,
                            Ilce = "Arpaçay,Digor,Kağızman,Merkez,Sarıkamış,Selim,Susuz,Akyaka",
                            Sehir = "Kars"
                        },
                        new
                        {
                            Id = 37,
                            Ilce = "Abana,Araç,Azdavay,Bozkurt,Cide,Çatalzeytin,Daday,Devrekani,İnebolu,Merkez,Küre,Taşköprü,Tosya,İhsangazi,Pınarbaşı,Şenpazar,Ağlı,Doğanyurt,Hanönü,Seydiler",
                            Sehir = "Kastamonu"
                        },
                        new
                        {
                            Id = 38,
                            Ilce = "Bünyan,Develi,Felahiye,İncesu,Pınarbaşı,Sarıoğlan,Sarız,Tomarza,Yahyalı,Yeşilhisar,Akkışla,Talas,Kocasinan,Melikgazi,Hacılar,Özvatan",
                            Sehir = "Kayseri"
                        },
                        new
                        {
                            Id = 39,
                            Ilce = "Babaeski,Demirköy,Merkez,Kofçaz,Lüleburgaz,Pehlivanköy,Pınarhisar,Vize",
                            Sehir = "Kırklareli"
                        },
                        new
                        {
                            Id = 40,
                            Ilce = "Çiçekdağı,Kaman,Merkez,Mucur,Akpınar,Akçakent,Boztepe",
                            Sehir = "Kırşehir"
                        },
                        new
                        {
                            Id = 41,
                            Ilce = "Gebze,Gölcük,Kandıra,Karamürsel,Körfez,Derince,Başiskele,Çayırova,Darıca,Dilovası,İzmit,Kartepe",
                            Sehir = "Kocaeli"
                        },
                        new
                        {
                            Id = 42,
                            Ilce = "Akşehir,Beyşehir,Bozkır,Cihanbeyli,Çumra,Doğanhisar,Ereğli,Hadim,Ilgın,Kadınhanı,Karapınar,Kulu,Sarayönü,Seydişehir,Yunak,Akören,Altınekin,Derebucak,Hüyük,Karatay,Meram,Selçuklu,Taşkent,Ahırlı,Çeltik,Derbent,Emirgazi,Güneysınır,Halkapınar,Tuzlukçu,Yalıhüyük",
                            Sehir = "Konya"
                        },
                        new
                        {
                            Id = 43,
                            Ilce = "Altıntaş,Domaniç,Emet,Gediz,Merkez,Simav,Tavşanlı,Aslanapa,Dumlupınar,Hisarcık,Şaphane,Çavdarhisar,Pazarlar",
                            Sehir = "Kütahya"
                        },
                        new
                        {
                            Id = 44,
                            Ilce = "Akçadağ,Arapgir,Arguvan,Darende,Doğanşehir,Hekimhan,Merkez,Pütürge,Yeşilyurt,Battalgazi,Doğanyol,Kale,Kuluncak,Yazıhan",
                            Sehir = "Malatya"
                        },
                        new
                        {
                            Id = 45,
                            Ilce = "Akhisar,Alaşehir,Demirci,Gördes,Kırkağaç,Kula,Merkez,Salihli,Sarıgöl,Saruhanlı,Selendi,Soma,Şehzadeler,Yunusemre,Turgutlu,Ahmetli,Gölmarmara,Köprübaşı",
                            Sehir = "Manisa"
                        },
                        new
                        {
                            Id = 46,
                            Ilce = "Afşin,Andırın,Dulkadiroğlu,Onikişubat,Elbistan,Göksun,Merkez,Pazarcık,Türkoğlu,Çağlayancerit,Ekinözü,Nurhak",
                            Sehir = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = 47,
                            Ilce = "Derik,Kızıltepe,Artuklu,Merkez,Mazıdağı,Midyat,Nusaybin,Ömerli,Savur,Dargeçit,Yeşilli",
                            Sehir = "Mardin"
                        },
                        new
                        {
                            Id = 48,
                            Ilce = "Bodrum,Datça,Fethiye,Köyceğiz,Marmaris,Menteşe,Milas,Ula,Yatağan,Dalaman,Seydikemer,Ortaca,Kavaklıdere",
                            Sehir = "Muğla"
                        },
                        new
                        {
                            Id = 49,
                            Ilce = "Bulanık,Malazgirt,Merkez,Varto,Hasköy,Korkut",
                            Sehir = "Muş"
                        },
                        new
                        {
                            Id = 50,
                            Ilce = "Avanos,Derinkuyu,Gülşehir,Hacıbektaş,Kozaklı,Merkez,Ürgüp,Acıgöl",
                            Sehir = "Nevşehir"
                        },
                        new
                        {
                            Id = 51,
                            Ilce = "Bor,Çamardı,Merkez,Ulukışla,Altunhisar,Çiftlik",
                            Sehir = "Niğde"
                        },
                        new
                        {
                            Id = 52,
                            Ilce = "Akkuş,Altınordu,Aybastı,Fatsa,Gölköy,Korgan,Kumru,Mesudiye,Perşembe,Ulubey,Ünye,Gülyalı,Gürgentepe,Çamaş,Çatalpınar,Çaybaşı,İkizce,Kabadüz,Kabataş",
                            Sehir = "Ordu"
                        },
                        new
                        {
                            Id = 53,
                            Ilce = "Ardeşen,Çamlıhemşin,Çayeli,Fındıklı,İkizdere,Kalkandere,Pazar,Merkez,Güneysu,Derepazarı,Hemşin,İyidere",
                            Sehir = "Rize"
                        },
                        new
                        {
                            Id = 54,
                            Ilce = "Akyazı,Geyve,Hendek,Karasu,Kaynarca,Sapanca,Kocaali,Pamukova,Taraklı,Ferizli,Karapürçek,Söğütlü,Adapazarı,Arifiye,Erenler,Serdivan",
                            Sehir = "Sakarya"
                        },
                        new
                        {
                            Id = 55,
                            Ilce = "Alaçam,Bafra,Çarşamba,Havza,Kavak,Ladik,Terme,Vezirköprü,Asarcık,Ondokuzmayıs,Salıpazarı,Tekkeköy,Ayvacık,Yakakent,Atakum,Canik,İlkadım",
                            Sehir = "Samsun"
                        },
                        new
                        {
                            Id = 56,
                            Ilce = "Baykan,Eruh,Kurtalan,Pervari,Merkez,Şirvan,Tillo",
                            Sehir = "Siirt"
                        },
                        new
                        {
                            Id = 57,
                            Ilce = "Ayancık,Boyabat,Durağan,Erfelek,Gerze,Merkez,Türkeli,Dikmen,Saraydüzü",
                            Sehir = "Sinop"
                        },
                        new
                        {
                            Id = 58,
                            Ilce = "Divriği,Gemerek,Gürün,Hafik,İmranlı,Kangal,Koyulhisar,Merkez,Suşehri,Şarkışla,Yıldızeli,Zara,Akıncılar,Altınyayla,Doğanşar,Gölova,Ulaş",
                            Sehir = "Sivas"
                        },
                        new
                        {
                            Id = 59,
                            Ilce = "Çerkezköy,Çorlu,Ergene,Hayrabolu,Malkara,Muratlı,Saray,Süleymanpaşa,Kapaklı,Şarköy,Marmaraereğlisi",
                            Sehir = "Tekirdağ"
                        },
                        new
                        {
                            Id = 60,
                            Ilce = "Almus,Artova,Erbaa,Niksar,Reşadiye,Merkez,Turhal,Zile,Pazar,Yeşilyurt,Başçiftlik,Sulusaray",
                            Sehir = "Tokat"
                        },
                        new
                        {
                            Id = 61,
                            Ilce = "Akçaabat,Araklı,Arsin,Çaykara,Maçka,Of,Ortahisar,Sürmene,Tonya,Vakfıkebir,Yomra,Beşikdüzü,Şalpazarı,Çarşıbaşı,Dernekpazarı,Düzköy,Hayrat,Köprübaşı",
                            Sehir = "Trabzon"
                        },
                        new
                        {
                            Id = 62,
                            Ilce = "Çemişgezek,Hozat,Mazgirt,Nazımiye,Ovacık,Pertek,Pülümür,Merkez",
                            Sehir = "Tunceli"
                        },
                        new
                        {
                            Id = 63,
                            Ilce = "Akçakale,Birecik,Bozova,Ceylanpınar,Eyyübiye,Halfeti,Haliliye,Hilvan,Karaköprü,Siverek,Suruç,Viranşehir,Harran",
                            Sehir = "Şanlıurfa"
                        },
                        new
                        {
                            Id = 64,
                            Ilce = "Banaz,Eşme,Karahallı,Sivaslı,Ulubey,Merkez",
                            Sehir = "Uşak"
                        },
                        new
                        {
                            Id = 65,
                            Ilce = "Başkale,Çatak,Erciş,Gevaş,Gürpınar,İpekyolu,Muradiye,Özalp,Tuşba,Bahçesaray,Çaldıran,Edremit,Saray",
                            Sehir = "Van"
                        },
                        new
                        {
                            Id = 66,
                            Ilce = "Akdağmadeni,Boğazlıyan,Çayıralan,Çekerek,Sarıkaya,Sorgun,Şefaatli,Yerköy,Merkez,Aydıncık,Çandır,Kadışehri,Saraykent,Yenifakılı",
                            Sehir = "Yozgat"
                        },
                        new
                        {
                            Id = 67,
                            Ilce = "Çaycuma,Devrek,Ereğli,Merkez,Alaplı,Gökçebey",
                            Sehir = "Zonguldak"
                        },
                        new
                        {
                            Id = 68,
                            Ilce = "Ağaçören,Eskil,Gülağaç,Güzelyurt,Merkez,Ortaköy,Sarıyahşi",
                            Sehir = "Aksaray"
                        },
                        new
                        {
                            Id = 69,
                            Ilce = "Merkez,Aydıntepe,Demirözü",
                            Sehir = "Bayburt"
                        },
                        new
                        {
                            Id = 70,
                            Ilce = "Ermenek,Merkez,Ayrancı,Kazımkarabekir,Başyayla,Sarıveliler",
                            Sehir = "Karaman"
                        },
                        new
                        {
                            Id = 71,
                            Ilce = "Delice,Keskin,Merkez,Sulakyurt,Bahşili,Balışeyh,Çelebi,Karakeçili,Yahşihan",
                            Sehir = "Kırıkkale"
                        },
                        new
                        {
                            Id = 72,
                            Ilce = "Merkez,Beşiri,Gercüş,Kozluk,Sason,Hasankeyf",
                            Sehir = "Batman"
                        },
                        new
                        {
                            Id = 73,
                            Ilce = "Beytüşşebap,Cizre,İdil,Silopi,Merkez,Uludere,Güçlükonak",
                            Sehir = "Şırnak"
                        },
                        new
                        {
                            Id = 74,
                            Ilce = "Merkez,Kurucaşile,Ulus,Amasra",
                            Sehir = "Bartın"
                        },
                        new
                        {
                            Id = 75,
                            Ilce = "Merkez,Çıldır,Göle,Hanak,Posof,Damal",
                            Sehir = "Ardahan"
                        },
                        new
                        {
                            Id = 76,
                            Ilce = "Aralık,Merkez,Tuzluca,Karakoyunlu",
                            Sehir = "Iğdır"
                        },
                        new
                        {
                            Id = 77,
                            Ilce = "Merkez,Altınova,Armutlu,Çınarcık,Çiftlikköy,Termal",
                            Sehir = "Yalova"
                        },
                        new
                        {
                            Id = 78,
                            Ilce = "Eflani,Eskipazar,Merkez,Ovacık,Safranbolu,Yenice",
                            Sehir = "Karabük"
                        },
                        new
                        {
                            Id = 79,
                            Ilce = "Merkez,Elbeyli,Musabeyli,Polateli",
                            Sehir = "Kilis"
                        },
                        new
                        {
                            Id = 80,
                            Ilce = "Bahçe,Kadirli,Merkez,Düziçi,Hasanbeyli,Sumbas,Toprakkale",
                            Sehir = "Osmaniye"
                        },
                        new
                        {
                            Id = 81,
                            Ilce = "Akçakoca,Merkez,Yığılca,Cumayeri,Gölyaka,Çilimli,Gümüşova,Kaynaşlı",
                            Sehir = "Düzce"
                        });
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BossId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CityId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("CityId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstiklal Caddesi, Beyoğlu, İstanbul, Türkiye",
                            BossId = 1,
                            CategoryId = 1,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2280),
                            Description = "Lezzetli et ürünleriyle hizmet veren kasap dükkanı.",
                            ImageUrl = "kasap.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@kasap.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2295),
                            Name = "Özgün Kasap",
                            PhoneNumber = "1234567890",
                            Url = "www.kasap.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bağdat Caddesi, Kadıköy, İstanbul, Türkiye",
                            BossId = 2,
                            CategoryId = 2,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2305),
                            Description = "Sağlık ürünleri ve ilaçların bulunduğu eczane.",
                            ImageUrl = "eczane.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@eczane.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2306),
                            Name = "Namık Eczanesi",
                            PhoneNumber = "1234567890",
                            Url = "www.eczane.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nişantaşı, Şişli, İstanbul, Türkiye",
                            BossId = 3,
                            CategoryId = 3,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2311),
                            Description = "Kalemlerden defterlere, kırtasiye malzemelerinin satıldığı dükkân.",
                            ImageUrl = "kirtasiye.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@kirtasiye.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2311),
                            Name = "Ozan Kırtasiyesi",
                            PhoneNumber = "1234567890",
                            Url = "www.kirtasiye.com"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Levent Mahallesi, Beşiktaş, İstanbul, Türkiye",
                            BossId = 4,
                            CategoryId = 4,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2316),
                            Description = "Kıyafet tamiratı ve dikimi yapan terzi dükkânı.",
                            ImageUrl = "terzi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@terzi.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2316),
                            Name = "Neşe Terzi",
                            PhoneNumber = "1234567890",
                            Url = "www.terzi.com"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bebek, Beşiktaş, İstanbul, Türkiye",
                            BossId = 5,
                            CategoryId = 5,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2322),
                            Description = "Diş sağlığı hizmetleri sunan dişçi kliniği.",
                            ImageUrl = "disci.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@disci.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2323),
                            Name = "İtina Dişçi",
                            PhoneNumber = "1234567890",
                            Url = "www.disci.com"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Moda Caddesi, Kadıköy, İstanbul, Türkiye",
                            BossId = 6,
                            CategoryId = 6,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2327),
                            Description = "Profesyonel hizmetlerle kiralık katil işleri yapan gizli dükkân.",
                            ImageUrl = "kiralik-katil.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@kiralik-katil.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2328),
                            Name = "Prof Kiralık Katil",
                            PhoneNumber = "1234567890",
                            Url = "www.kiralik-katil.com"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Sultanahmet Meydanı, Fatih, İstanbul, Türkiye",
                            BossId = 7,
                            CategoryId = 7,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2332),
                            Description = "Fitness ve spor salonu.",
                            ImageUrl = "gym.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@gym.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2333),
                            Name = "Şişman Gym",
                            PhoneNumber = "1234567890",
                            Url = "www.gym.com"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ortaköy, Beşiktaş, İstanbul, Türkiye",
                            BossId = 8,
                            CategoryId = 8,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2338),
                            Description = "Lezzetli mantı çeşitlerinin servis edildiği mantı dükkânı.",
                            ImageUrl = "mantici.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@mantici.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2338),
                            Name = "Enfes Mantıcı",
                            PhoneNumber = "1234567890",
                            Url = "www.mantici.com"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Kadıköy İskelesi, Kadıköy, İstanbul, Türkiye",
                            BossId = 9,
                            CategoryId = 9,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2342),
                            Description = "Futbol oynamak için ideal bir saha.",
                            ImageUrl = "futbol-sahasi.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@futbol-sahasi.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2343),
                            Name = "Yeşil Futbol Sahası",
                            PhoneNumber = "1234567890",
                            Url = "www.futbol-sahasi.com"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Taksim Meydanı, Beyoğlu, İstanbul, Türkiye",
                            BossId = 10,
                            CategoryId = 10,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2348),
                            Description = "Ayakkabı tamir ve bakımı yapan lostra dükkânı.",
                            ImageUrl = "lostra.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@lostra.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2348),
                            Name = "Dikkat Lostra",
                            PhoneNumber = "1234567890",
                            Url = "www.lostra.com"
                        },
                        new
                        {
                            Id = 11,
                            Address = "İstiklal Caddesi, Beyoğlu, İstanbul, Türkiye",
                            BossId = 1,
                            CategoryId = 11,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2352),
                            Description = "Sevilen mahalle bakkal amcanız.",
                            ImageUrl = "bakkal.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@rafik-kasap.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2353),
                            Name = "Rafık Bakkal",
                            PhoneNumber = "1234567890",
                            Url = "www.rafik-bakkal.com"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Ümraniye, İstanbul, Türkiye",
                            BossId = 2,
                            CategoryId = 12,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2358),
                            Description = "Lezzetli yemekler sunan restoran.",
                            ImageUrl = "restoran.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@lezzet-restoran.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2358),
                            Name = "Lezzet Restoran",
                            PhoneNumber = "1234567890",
                            Url = "www.lezzet-restoran.com"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Bahçe Sokak, Ankara, Türkiye",
                            BossId = 3,
                            CategoryId = 13,
                            CityId = 6,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2362),
                            Description = "Keyifli bir ortamda kahve ve atıştırmalıklar sunan kafe.",
                            ImageUrl = "kafe.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@keyifli-kafe.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2363),
                            Name = "Keyifli Kafe",
                            PhoneNumber = "1234567890",
                            Url = "www.keyifli-kafe.com"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Bağdat Caddesi, Kadıköy, İstanbul, Türkiye",
                            BossId = 4,
                            CategoryId = 14,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2367),
                            Description = "Moda ve stilin buluştuğu şık butik mağaza.",
                            ImageUrl = "butik.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@sik-butik.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2367),
                            Name = "Şık Butik",
                            PhoneNumber = "1234567890",
                            Url = "www.sik-butik.com"
                        },
                        new
                        {
                            Id = 15,
                            Address = "İzmir Caddesi, İzmir, Türkiye",
                            BossId = 5,
                            CategoryId = 15,
                            CityId = 35,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2371),
                            Description = "Gözlük ve güneş gözlüğü mağazası.",
                            ImageUrl = "optik.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@net-optik.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2372),
                            Name = "Net Optik",
                            PhoneNumber = "1234567890",
                            Url = "www.net-optik.com"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Bağlar Sokak, Bursa, Türkiye",
                            BossId = 6,
                            CategoryId = 16,
                            CityId = 16,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2377),
                            Description = "Konforlu ve şık mobilyaların satıldığı mağaza.",
                            ImageUrl = "mobilya.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@rahat-mobilya.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2377),
                            Name = "Rahat Mobilya Mağazası",
                            PhoneNumber = "1234567890",
                            Url = "www.rahat-mobilya.com"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Çocuklar Caddesi, Antalya, Türkiye",
                            BossId = 7,
                            CategoryId = 17,
                            CityId = 7,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2383),
                            Description = "Eğlenceli ve renkli oyuncakların satıldığı oyuncakçı dükkanı.",
                            ImageUrl = "oyuncakci.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@neseli-oyuncakci.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2384),
                            Name = "Neşeli Oyuncakçı",
                            PhoneNumber = "1234567890",
                            Url = "www.neseli-oyuncakci.com"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Teknoloji Sokak, İzmit, Kocaeli Türkiye",
                            BossId = 8,
                            CategoryId = 18,
                            CityId = 41,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2388),
                            Description = "Son teknoloji elektronik ürünlerin satıldığı mağaza.",
                            ImageUrl = "elektronik.jpg",
                            IsActive = false,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@teknoloji-elektronik.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2388),
                            Name = "Teknoloji Elektronik Mağaza",
                            PhoneNumber = "1234567890",
                            Url = "www.teknoloji-elektronik.com"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Çiçekler Sokak, Adana, Türkiye",
                            BossId = 9,
                            CategoryId = 19,
                            CityId = 1,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2392),
                            Description = "Canlı ve renkli çiçeklerin satıldığı çiçekçi dükkanı.",
                            ImageUrl = "cicekci.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            MailAdress = "info@renkli-cicekci.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2393),
                            Name = "Renkli Çiçekçi",
                            PhoneNumber = "1234567890",
                            Url = "www.renkli-cicekci.com"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Kitaplar Sokak, İstanbul, Türkiye",
                            BossId = 10,
                            CategoryId = 20,
                            CityId = 34,
                            CreatedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2397),
                            Description = "Geniş bir kitap koleksiyonuna sahip olan kitapçı.",
                            ImageUrl = "kitapci.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            MailAdress = "info@bilge-kitapci.com",
                            ModifiedDate = new DateTime(2023, 7, 11, 15, 49, 16, 765, DateTimeKind.Local).AddTicks(2397),
                            Name = "Bilge Kitapçı",
                            PhoneNumber = "1234567890",
                            Url = "www.bilge-kitapci.com"
                        });
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.Shop", b =>
                {
                    b.HasOne("WhatWhere.Entity.Concrete.Boss", "Boss")
                        .WithMany("Shops")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("WhatWhere.Entity.Concrete.Category", "Category")
                        .WithOne()
                        .HasForeignKey("WhatWhere.Entity.Concrete.Shop", "CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatWhere.Entity.Concrete.City", "City")
                        .WithMany("Shops")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Category");

                    b.Navigation("City");
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.Boss", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("WhatWhere.Entity.Concrete.City", b =>
                {
                    b.Navigation("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
